from django import forms

class PrediccionGRDForm(forms.Form):
    edad = forms.FloatField(required=False, label="Edad")
    sexo = forms.CharField(required=False, label="Sexo")
    tipo_ingreso = forms.CharField(required=False, label="Tipo de ingreso")
    dias_estancia = forms.FloatField(required=False, label="Días de estancia")
    servicio_alta = forms.CharField(required=False, label="Servicio de alta")
    dias_uci = forms.FloatField(required=False, label="Días de Unidad de Cuidados Intensivos")
    dx_principal_egreso = forms.CharField(required=False, label="Dx principal de egreso")
    dxr1 = forms.CharField(required=False, label="Dxr 1")
    dxr2 = forms.CharField(required=False, label="Dxr 2")
    dxr3 = forms.CharField(required=False, label="Dxr 3")
    dxr4 = forms.CharField(required=False, label="Dxr 4")
    dxr5 = forms.CharField(required=False, label="Dxr 5")
    dxr6 = forms.CharField(required=False, label="Dxr-6")
    dxr7 = forms.CharField(required=False, label="Dxr 7")
    dxr8 = forms.CharField(required=False, label="Dxr 8")
    dxr9 = forms.CharField(required=False, label="Dxr 9")
    codigo_causa_externa = forms.CharField(required=False, label="Código causa externa")
    situacion_alta = forms.CharField(required=False, label="Situación al alta")
    proc1 = forms.CharField(required=False, label="Procedimiento 1")
    proc2 = forms.CharField(required=False, label="Procedimiento 2")
    proc3 = forms.CharField(required=False, label="Procedimiento 3")
    proc4 = forms.CharField(required=False, label="Procedimiento 4")
    proc5 = forms.CharField(required=False, label="Procedimiento 5")
    proc6 = forms.CharField(required=False, label="Procedimiento 6")
    proc7 = forms.CharField(required=False, label="Procedimiento 7")
    proc8 = forms.CharField(required=False, label="Procedimiento 8")
    proc9 = forms.CharField(required=False, label="Procedimiento 9")
    proc10 = forms.CharField(required=False, label="Procedimiento 10")
    proc11 = forms.CharField(required=False, label="Procedimiento 11")
    proc12 = forms.CharField(required=False, label="Procedimiento 12")
    tipo_servicio = forms.CharField(required=False, label="Tipo de servicio")
    infecciones = forms.CharField(required=False, label="Infecciones")
